[project]
name = "odoo-addons-oca-hr-attendance"
version = "17.0.20240812.0"
dependencies = [
    "odoo-addon-hr_attendance_calendar_view>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
